language: node_js
node_js:
  - "6"
script:
  - npm run test

after_success:
  - npm install codeclimate-test-reporter -g
  - npm run coverage

addons:
  code_climate:
    repo_token: yss3uAPO4d37EcrMY4V9SNlRP8twCg0U4