language: node_js

node_js:
  - "6"

before_install:
- npm install -g mocha

before_script:
  - npm install

script: 
  - npm run test

after_success:
  - npm install codeclimate-test-reporter -g
  - npm run coverage